### ISSUE TITLE
Could you tell me your model like Table 2 15.8M in your paper?

### ISSUE THREAD

**Issue by ghost** [Ereboas/TacoLM#1]
Thanks for sharing your great work!

Now, I am reproducing your paper result but I'm not finding your model like Table 2 15.8M in your paper

![Screenshot 2024-07-13 at 9 48 49 PM](https://github.com/user-attachments/assets/d6caef5f-d6b0-4d73-be64-81e8fb89b85d)

Could you tell me the model idx in mega_lm in fairseq? 

Now I'am guessing.. mega_pa_valle_09?
![Screenshot 2024-07-13 at 9 51 22 PM](https://github.com/user-attachments/assets/35146c1c-acde-448a-9fb5-1d8de6cd90df)

Best regards
Seung Woo

**Comment by samkat94** [comment]
Hello @yuseungwoo were you able to find the model? I am trying to reproduce the paper result as well but not finding the model.
